name: Check bilara data

on:
  push:
    branches:
      - published

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout sc_renumber_segments
      uses: actions/checkout@v2
      with:
        repository: suttacentral/sc-renumber-segments
        path: sutta_processor
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('sutta_processor/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -e ./sutta_processor
    - name: Run Bilara-Data checks
      run: sutta-processor -c ${GITHUB_WORKSPACE}/.github/sc-renumber-segments-settings.yaml
