name: Move published bilara data to sc-data

on:
  push:
    branches:
      - published

jobs:
  move-data-with-nilakkhana-transform:
    runs-on: ubuntu-20.04
    
    env:
      FROM_REPO: dayunbao/bilara-data
      FROM_REPO_BRANCH: published
      TO_REPO: dayunbao/sc-data
      TO_REPO_BRANCH: master
      TO_REPO_TARGET_FOLDER: sc_bilara_data
      PYTHON_VERSION: 3.7.5
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    steps:
      - name: Checkout ${{ env.FROM_REPO }} repo
        uses: actions/checkout@v2 
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: ${{ env.FROM_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.FROM_REPO_BRANCH }}
          path: from-repo

      - name: Checkout ${{ env.TO_REPO }} repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.TO_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.TO_REPO_BRANCH }}
          path: to-repo

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install python dependencies
        run: pip install -r from-repo/nilakkhana/requirements.txt

      - name: Perform Nilakkhana transformation
        run: python from-repo/nilakkhana/parse.py

      - name: Create target directory if not exists
        run: mkdir -p to-repo/$TO_REPO_TARGET_FOLDER

      - name: Remove from-repo README.md
        run: |
          cd from-repo
          rm README.md

      - name: Copy changed files to the target directory
        run: cp -r from-repo/* to-repo/$TO_REPO_TARGET_FOLDER/

      - name: Push ${{ env.TO_REPO }}
        run: |
          cd to-repo
          git config --global user.name "dayunbao"
          git config --global user.email "11196050+dayunbao@users.noreply.github.com"
          git remote set-url --push origin https://dayunbao:$GITHUB_TOKEN@github.com/dayunbao/sc-data
          git add .
          git commit -m "From bilara published"
          git push
